### ISSUE TITLE
Creepers destroy chest and items don't drop

### ISSUE THREAD

**Issue by k9lego** [JEFF-Media-GbR/Spigot-AngelChest#2]
When a creeper or fire destroys the chest, nothing is dropped. Could you add a functionality that prevents it from being destroyed by natural elements?

**Comment by mfnalex** [comment]
Actually, that is not so easy, because I can only cancel the whole creeper explosion or do not cancel it at all. Also, creepers can destroy normal chests anyway, so I don't think it's a problem. But if other people also request this, I will try to add it :)

**Comment by k9lego** [comment]
Well the main issue is the chest does not drop anything. So the chest is only dropped and all the other items are lost. This is a bug. :)

**Comment by kaimokene** [comment]
Ive lost countless of items to a ender dragon/creeper breaking the ender chest. So i would like it to be fixed aswell.

**Comment by mfnalex** [comment]
I have added this. Creepers and other entities can no longer destroy AngelChests with explosions. Thanks for reminding me again.
