### ISSUE TITLE
[Suggest] Let AngelChest support player_head material

### ISSUE THREAD

**Issue by Pau1am** [JEFF-Media-GbR/Spigot-AngelChest#28]
I hope this plugin can support player_head as a material, and can modify the effect of AngelChest's skin by modifying the ID of player_head

**Comment by mfnalex** [comment]
When you set material to player_head, it uses the player's skin's head. Do you want to be able to use a fully a custom head?

**Comment by Pau1am** [comment]
> When you set material to player_head, it uses the player's skin's head. Do you want to be able to use a fully a custom head?

Yes

**Comment by mfnalex** [comment]
Unfortunately, I don't think there is a method in the Spigot API to do that. There are some dirty hacks to get this working though. I will have a look at what I can do. You don't use 1.12 though, do you?

**Comment by Pau1am** [comment]
Yes, the version I am using is 1.16.1

**Comment by mfnalex** [comment]
I will get this to work somehow, maybe today

**Comment by mfnalex** [comment]
fixed in version 2.10.0 d4a8a099dfe39d0a8a715e736f48e30e4ed74556
