### ISSUE TITLE
1.13.1 doesn't always spawn chest

### ISSUE THREAD

**Issue by stevenesser** [JEFF-Media-GbR/Spigot-AngelChest#3]
The chest was spawned with message notification perfectly while I tested it with a /kill name as op. It doesn't seem to work for any type of death however since, whether that be drowning or getting killed by a mob. 
Strange stuff. Could it be the setting I changed from 10 minutes to 1 hour? Or is this a story where I am running 1.13.1 and the plugin is meant for 1.13.0?

**Comment by mfnalex** [comment]
It works fine in 1.13.1. Maybe you have some other plugin installed that interferes with the OnDeathEvent? Could you please try disabling all other plugins? (Just rename your plugins directory and create a new one with just AngelChest in it). It should actually work fine.

**Comment by stevenesser** [comment]
will try yes. The other plugin was GriefPrevention

**Comment by mfnalex** [comment]
Did it work?

**Comment by stevenesser** [comment]
I haven't tried it. I have actually stopped using the plugin and instead
installed a datapack that does the same thing.

Steven

**Comment by mfnalex** [comment]
By the way, this has been fixed a long time ago.
