### ISSUE TITLE
ignore-keep-inventory not working correctly

### ISSUE THREAD

**Issue by Kikisito** [JEFF-Media-GbR/Spigot-AngelChest#31]
Hello. Today I had an issue with AngelChests and the ignore-keep-inventory option. While having it disabled (false), I died and I lost all my items. I have keepInventory enabled via EssentialsX.

While debugging and trying to see what's happening, I saw that AngelChests actually ignores keepInventory when the option is disabled. Meanwhile, when it's enabled, you actually lose all your items and no chest is generated in any way.

![Debug](https://i.imgur.com/HcfkpPd.png)

About getting the drops cleared, I have no plugins that clears my drops, and as I told you before, If I enable _ignore-keep-inventory_, my drops are not erased.

Edit: No errors are shown in the log.

**Comment by mfnalex** [comment]
You definitely have a plugin that clears the drops, probably essentials as you have the essentials.keepinv permission. Please post the output of /plugins

I will have a look at the ignore setting tomorrow

**Comment by Kikisito** [comment]
`Plugins (73): ActionHealth*, AngelChest, AntiVanillaPortals, AsyncWorldEdit, BeeHivesTrees, BungeeTabListPlus, ChatSlowMode*, Citizens, ColoredAnvils, CommandHook, CoreProtect, DeathCoordinates, DeathMessagesPrime, DenySpawnerChange, DisableJoinMessage*, dynmap*, Elevator, EntityDetection, EntityTrackerFixer, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, Fe*, Fricore, GPS, HeadNamer, HolographicDisplays, Images, LibsDisguises, LimitPillagers, LuckPerms, LWC, MagicBottle, MarriageMaster, MaSuiteCore, MaSuitePortals, MaSuiteWarps, MinecartSpeedPlus*, MultiChat*, Multiverse-Core, Multiverse-Portals, MyCommand, NametagEdit*, NFCNotes, OnDeathCoord*, paperautoupdate, ParrotGlue, PerWorldInventory, Phantom-B-Gone, PlayerHeads, PluginConstructorAPI, PlugMan, PowerlessLamps*, PremiumVanish, ProtocolLib, RFChairs, Shopkeepers, Sickle, SignEdit, SuperbVote, TogglePvp*, Trash*, UberEnchant, UltimateTimber, Vault, Votifier, WeatherVote, WithdrawToNFCNotes, WorldBorder, WorldEdit, WorldGuard`

> You definitely have a plugin that clears the drops, probably essentials as you have the essentials.keepinv permission. Please post the output of /plugins

That permissions just makes you keep your inventory, but it doesn't clear your drops. I've just checked it on the [EssentialsX PlayerDeathEvent](https://github.com/EssentialsX/Essentials/blob/a1297feb9dad02eb349589f9cbfb4a5b265e41ed/Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java#L162) listener.

Edit 1: I've tried it without PerWorldInventory and the issue still appears. I still checking.

**Comment by mfnalex** [comment]
Thank you, I will check that tomorrow. I don't have time today, sorry.

However, AngelChest also does not clear your drops unless it creates a chest, so I don't really know what the problem is right now. Will check and fix ASAP

**Comment by mfnalex** [comment]
The check was indeed the wrong way around. Please check if this fixes it: https://repo.jeff-media.de/maven2/de/jeff_media/AngelChest/2.14.3-SNAPSHOT/AngelChest-2.14.3-20200724.185840-1.jar

**Comment by Kikisito** [comment]
Hello again. I've checked the version you gave me and the ignore-keep-inventory works perfectly. Regarding the cleared drops, I found I was wrong and it came from Essentials but I still don't know why that happens. I'll tell you if I find something.

Thanks for your support!

**Comment by Kikisito** [comment]
I've been checking what's causing the drops issue and I saw that I got the wrong listener file from EssentialsX. Sorry for that mistake. The actual one is [this file](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java#L178), which clear drops when a player with the permission _keepinv_ dies. 

This issue can actually be fixed by setting lowest priority to AngelChest's PlayerDeath listener. I've just tested it on my test server.

**Comment by mfnalex** [comment]
Thanks for the reply :) i will have a look at that tomorrow or next week

**Comment by mfnalex** [comment]
thanks for the PR, released as 2.14.3

**Comment by mfnalex** [comment]
do you have discord?

**Comment by Kikisito** [comment]
I do. Kikisito#2106

**Comment by mfnalex** [comment]
Oh, you don't accept friend requests^^ If you like, please join my discord https://discord.jeff-media.de

**Comment by Kikisito** [comment]
Forgot about that, I've already sent you a friend request
