### ISSUE TITLE
Spawning and teleporting to wrong locations

### ISSUE THREAD

**Issue by noramibu** [JEFF-Media-GbR/Spigot-AngelChest#39]
When players killed by a mob (usually skeleton) chest is not spawning on same coordinates (spawning on near 2 or 3 block) and when players do actp they are spawning inside of a wall 

Video: https://cdn.discordapp.com/attachments/732403539355107429/751579906583822366/AngelChest_Bug.mp4
Config: https://cdn.discordapp.com/attachments/734035785833250876/751568061987029142/config.yml

**Comment by mfnalex** [comment]
This was the missing CAVE_AIR in the config, right?

**Comment by noramibu** [comment]
Yeah, this was.
