### ISSUE TITLE
Chests disappearing on server restart

### ISSUE THREAD

**Issue by javieralvarezlo** [JEFF-Media-GbR/Spigot-AngelChest#41]
Just this. When you restart the server with an Angel Chest placed, it desappears and the items inside it with it.

**Comment by mfnalex** [comment]
Please enable the debug mode in your config.yml, then restart the server. Then create an Angelchest, shutdown the server then send your latest.log, restart the server again and send your latest.log again.

**Comment by javieralvarezlo** [comment]
Okey, I have seen and I was using an outdated version (2.4.0). I've tried the newest version and it works properly. Do you know in which version was it fixed? I don't wanna update the whole plugin, it has lots of feratures that i'm not going to use and I want to keep it as much lightweight as possible. Tahnk you!

**Comment by mfnalex** [comment]
Sorry, but please always use the latest version. You don't have to use all the new features - many improvements are bug fixes, so I cannot give support for old versions. I will close this issue now but feel free to reply for any further questions.

**Comment by mfnalex** [comment]
I can promise you that the latest version will NOT use more resources than old ones :)
