### ISSUE TITLE
[Suggestion] Add cost for Angelchest to be summoned.

### ISSUE THREAD

**Issue by Ryant22** [JEFF-Media-GbR/Spigot-AngelChest#42]
I'd like to be able to charge players for the privilege of having their items collected into the chests. 
If the player doesn't have the balance available to deduct from their balance - The chest shouldn't initialize and the vanilla behavior should play out.

**Comment by mfnalex** [comment]
Awesome idea, will be added - PRs welcome

**Comment by mfnalex** [comment]
added in 2.19.0-SNAPSHOT, will be released soon
