### ISSUE TITLE
[FEATURE-REQUEST] Loot messages and open messages

### ISSUE THREAD

**Issue by DavidRSM29** [JEFF-Media-GbR/Spigot-AngelChest#49]
Hi, could it be possible to add a message to be broadcast when a player who is not the owner of the AngelChest opens it or steals the chest?

**Comment by mfnalex** [comment]
Sure! Are you using the plus (paid) or free version?

**Comment by DavidRSM29** [comment]
plus, and if you need to confirm the purchase, I just follow you on spigot with an account named Nakamaverse.

**Comment by mfnalex** [comment]
It has been added in AngelChestPlus 1.10.0 :)
