### ISSUE TITLE
super dupe bug epic no clickbait

### ISSUE THREAD

**Issue by matipoirierg** [JEFF-Media-GbR/Spigot-AngelChest#51]
Using latest version of the plugin premium 9.8.0, purpur 1.19.3
https://youtu.be/9NbjpNU69FI

**Comment by mfnalex** [comment]
Looks like you're using the paid version. Please open a ticket on my discord: https://discord.jeff-media.com/

**Comment by mfnalex** [comment]
fixed in 9.9.0
