### ISSUE TITLE
Bug: Players loose access to chest if they get disconnected

### ISSUE THREAD

**Issue by Boastful1353** [JEFF-Media-GbR/Spigot-AngelChest#6]
The plugin incorrectly tells players the chest does not belong to them if they disconnect or loose connection, then they are forced to wait around till the timer runs out if an admin isn't online.

**Comment by mfnalex** [comment]
That should not happen. When a player disconnects or the server restarts, the chest should drop its contents. What version of Spigot and AngelChest are you running?

PS. I am planning to add a feature so that AngelChests survive disconnects/restarts, however I dont not have much time right now.

**Comment by mfnalex** [comment]
This has been fixed as of 1.5
