### ISSUE TITLE
Material must be a block

### ISSUE THREAD

**Issue by Kikisito** [JEFF-Media-GbR/Spigot-AngelChest#8]
Hi, after using AngelChest, we've seen this error when an user dies while it's on a sapling, dead bush, torch, or any other block like this.

> [17:08:44 WARN]: java.lang.IllegalArgumentException: Material must be a block!
> [17:08:44 WARN]: at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
> [17:08:44 WARN]: at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.setType(CraftBlockState.java:127)
> [17:08:44 WARN]: at net.coreprotect.consumer.Queue.queueContainerBreak(Queue.java:118)
> [17:08:44 WARN]: at net.coreprotect.database.Database.containerBreakCheck(Database.java:70)
> [17:08:44 WARN]: at net.coreprotect.listener.EntityListener.onEntityDamageByEntity(EntityListener.java:246)
> [17:08:44 WARN]: at sun.reflect.GeneratedMethodAccessor160.invoke(Unknown Source)
> [17:08:44 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [17:08:44 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [17:08:44 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
> [17:08:44 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [17:08:44 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
> [17:08:44 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
> [17:08:44 WARN]: at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:100)
> [17:08:44 WARN]: at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:663)
> [17:08:44 WARN]: at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:562)
> [17:08:44 WARN]: at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:714)
> [17:08:44 WARN]: at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:700)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.EntityArmorStand.damageEntity(EntityArmorStand.java:413)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.EntityHuman.attack(EntityHuman.java:1050)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.EntityPlayer.attack(EntityPlayer.java:1334)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1876)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:69)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInUseEntity.a(SourceFile:13)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
> [17:08:44 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [17:08:44 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
> [17:08:44 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
> [17:08:44 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by mfnalex** [comment]
Thanks. Are you using spigot or bukkit?

**Comment by mfnalex** [comment]
Seems like there is a problem with CoreProtect? I will have a look tomorrow.

**Comment by mfnalex** [comment]
I tried killing myself inside a torch with latest Spigot 1.13.2 and latest version of CoreProtect. Everything works fine and I get no error at all. The AngelChest was spawned directly next to the torch. Please send the following infos:
- Version of Spigot
- Version of CoreProtect
- Version of AngelChest

**Comment by Kikisito** [comment]
I'm using Spigot 1.13.2 R0.1-Snapshot and CoreProtect 2.15.1, with AngelChest 1.5.1

**Comment by mfnalex** [comment]
Please post the output of /version

**Comment by mfnalex** [comment]
And please give a list of all plugins you are using. Thanks.

**Comment by Kikisito** [comment]
Here you have everything:
http://prntscr.com/lica7f

**Comment by mfnalex** [comment]
Please try again using only AngelChest, CoreProtect and the latest Spigot. I could not reproduce the problem, and many servers use AngelChest and CoreProtect together, including myself.

As you can see, the message does NOT come from AngelChest, because the package name "de.jeffclan.AngelChest" does not appear in the stack trace. That means, some other plugin produces the message.

**Comment by mfnalex** [comment]
Closed. This is not a problem created by AngelChest. You can reopen this if you have more infos or tried with only AngelChest, CoreProtect and latest Spigot.
